openapi: 3.1.0
info:
  version: 1.0.0
  title: Contact gallery app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of contact gallery app
tags:
  - name: Contacts
    description: Operations about contacts.
servers:
  - url: https://contacts-app-swagger-hgem.onrender.com
paths:
  /contacts:
    get:
      $ref: '../swagger/paths/students/get.yaml'
    post:
      $ref: '../swagger/paths/students/post.yaml'
  /contacts/{id}:
    get:
      $ref: '../swagger/paths/students/{id}/get.yaml'
    delete:
      $ref: '../swagger/paths/students/{id}/delete.yaml'
    patch:
      $ref: '../swagger/paths/students/{id}/patch.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
